<?php
/**
 * @file
 * sc_f_ct_school_infrastructure.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function sc_f_ct_school_infrastructure_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance:
  // 'node-ct_school_infrastructure-field_ct_infrastructure'.
  $field_instances['node-ct_school_infrastructure-field_ct_infrastructure'] = array(
    'bundle' => 'ct_school_infrastructure',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'field_collection',
        'settings' => array(
          'add' => 'Add',
          'delete' => 'Delete',
          'description' => TRUE,
          'edit' => 'Edit',
          'view_mode' => 'full',
        ),
        'type' => 'field_collection_view',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_ct_infrastructure',
    'label' => 'Infrastructure',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'field_collection',
      'settings' => array(),
      'type' => 'field_collection_embed',
      'weight' => 4,
    ),
  );

  // Exported field_instance: 'node-ct_school_infrastructure-field_ct_school'.
  $field_instances['node-ct_school_infrastructure-field_ct_school'] = array(
    'bundle' => 'ct_school_infrastructure',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'entityreference',
        'settings' => array(
          'link' => FALSE,
        ),
        'type' => 'entityreference_label',
        'weight' => 1,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_ct_school',
    'label' => 'school',
    'required' => 1,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => 3,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Infrastructure');
  t('school');

  return $field_instances;
}
