
<?php
/**
 * @file
 * Contains general function for Sakal jain samaj site.
 */

define('MODULE_PATH', drupal_get_path('module', 'schoolcounter_general_apis'));

/**
 * Implements hook_page_alter().
 */
function schoolcounter_general_apis_page_alter(&$page) {

  $path = current_path();
  $alias = drupal_get_path_alias($path);
  $theme_path = drupal_get_path('theme', 'schoolcounter_theme');

  if (drupal_is_front_page()) {
    $slick_lib = libraries_get_path('slick');
    drupal_add_css($slick_lib . '/slick/slick.css', 'file');
    drupal_add_css($slick_lib . '/slick/slick-theme.css', 'file');
    drupal_add_js($slick_lib . '/slick/slick.js', 'file');
    drupal_add_js($slick_lib . '/slick/slick.min.js', 'file');
    drupal_add_js($theme_path . '/javascripts/homepage.js', 'file');
    drupal_add_css($theme_path . '/css/home.css', 'file');
  }

  switch ($path) {
    case 'school':
      // drupal_add_js($theme_path . '/javascripts/homepage.js', 'file');
      drupal_add_css($theme_path . '/css/school.css', 'file');
    break;
    case 'school-blogs':
      drupal_add_css($theme_path . '/css/blogs_landing.css', 'file');
    break;

  }

  if (arg(0) == 'events') {
    drupal_add_css($theme_path . '/css/event_page.css', 'file');
  }
  if (arg(0) == 'teachers') {
    drupal_add_css($theme_path . '/css/faculty.css', 'file');
  }
}

/**
 * Implements hook_node_view().
 */
function schoolcounter_general_apis_node_view($node, $view_mode, $langcode) {
  $theme_path = drupal_get_path('theme', 'schoolcounter_theme');
  $slick_lib = libraries_get_path('slick');
  $jscroll_lib = libraries_get_path('jScroll');

  if ($node->type == 'ct_school') {
    drupal_add_css($slick_lib . '/slick/slick.css', 'file');
    drupal_add_css($slick_lib . '/slick/slick-theme.css', 'file');
    drupal_add_js($slick_lib . '/slick/slick.js', 'file');
    drupal_add_js($slick_lib . '/slick/slick.min.js', 'file');
    drupal_add_js($theme_path . '/javascripts/school-node.js', 'file');
    drupal_add_css($theme_path . '/css/school-node.css', 'file');

    drupal_add_js($jscroll_lib . '/jquery.jscrollpane.min.js', 'file');
    drupal_add_js($jscroll_lib . '/jquery.mousewheel.js', 'file');
    drupal_add_css($jscroll_lib . '/jquery.jscrollpane.css', 'file');
  }

  if ($node->type == 'ct_events') {
    drupal_add_css($slick_lib . '/slick/slick.css', 'file');
    drupal_add_css($slick_lib . '/slick/slick-theme.css', 'file');
    drupal_add_js($slick_lib . '/slick/slick.js', 'file');
    drupal_add_js($slick_lib . '/slick/slick.min.js', 'file');
    drupal_add_js($theme_path . '/javascripts/event_node.js', 'file');
    drupal_add_css($theme_path . '/css/event_node.css', 'file');
  }
}
